# wrangler.toml
name = "ai-daily"
main = "src/index.js"
compatibility_date = "2025-05-20"
workers_dev = true

kv_namespaces = [
  { binding = "DATA_KV", id = "你的kv-id" }
]

[vars]
IMG_PROXY = ""
OPEN_TRANSLATE = "true"
USE_MODEL_PLATFORM = "GEMINI"
GEMINI_API_KEY = "AIzaSyD3wQaGJUQ_70cWNVIqo6pGwf9Y30S4YCk"
GEMINI_API_URL = "https://api-proxy.me/gemini"
DEFAULT_GEMINI_MODEL = "gemini-2.5-flash-preview-05-20"
OPENAI_API_KEY = "sk-xxxxxx"
OPENAI_API_URL = "https://api.deepseek.com"
DEFAULT_OPEN_MODEL = "deepseek-chat"
FOLO_COOKIE_KV_KEY = "folo_auth_cookie"
FOLO_DATA_API = "https://api.follow.is/entries"
FOLO_FILTER_DAYS = 1
NEWS_AGGREGATOR_LIST_ID = "158437828119024640"
NEWS_AGGREGATOR_FETCH_PAGES = "1"
HGPAPERS_LIST_ID = "158437917409783808"
HGPAPERS_FETCH_PAGES = "1"
TWITTER_LIST_ID = "153028784690326528"
TWITTER_FETCH_PAGES = "1"
REDDIT_LIST_ID = "167576006499975168"
REDDIT_FETCH_PAGES = "1"
PROJECTS_API_URL = "https://git-trending.justlikemaki.vip/topone/?since=daily"
GITHUB_TOKEN = "github_pat_xxxxxx"
GITHUB_REPO_OWNER = "tripleprism"
GITHUB_REPO_NAME = "CloudFlare-AI-Insight-Daily"
GITHUB_BRANCH = "main"
LOGIN_USERNAME = "root"
LOGIN_PASSWORD = "toor"
DAILY_TITLE = "AI洞察日报"
DAILY_TITLE_MIN = "AI日报"
PODCAST_TITLE = "柚子小酒馆"
PODCAST_BEGIN = "嘿，亲爱的柚子er,我是你们的AI老朋友，来生"
PODCAST_END = "今天的情报就到这里，注意隐蔽，赶紧撤离"
INSERT_FOOT = "false"
INSERT_AD = "false"
